### ISSUE TITLE
run command --run_ep True m3b error

### ISSUE THREAD

**Issue by iamfaith** [gelman/ep-stan#2]
run command: python /Users/faith/ep-stan/experiment/fit.py --run_ep True m3b

output:

Configurations:
    J = 64
    D = 16
    npg = 20
    cor_input = True
    run_all = False
    run_ep = True
    run_snep = False
    run_full = False
    run_consensus = False
    run_target = False
    iter = None
    siter = 200
    target_siter = 10000
    chains = 4
    K = 32
    damp = None
    mix = False
    prec_estim = 'sample'
    seed_data = 100
    seed_ep = 1
    seed_full = 2
    seed_cons = 3
    seed_target = 4
    id = None
    save_true = True
    save_res = True
    save_target_samp = False
True values saved into results
Distributed EP method
Run distributed EP algorithm for 128 iterations.
Iter 0.5 starting, df: 1 
Process tilted distributions
    site 1 Process Process-1:
Traceback (most recent call last):
  File "/Users/faith/anaconda3/envs/py3.7/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/Users/faith/anaconda3/envs/py3.7/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/faith/ep-stan/epstan/method.py", line 93, in _sample_stan
    samp = copy_fit_samples(fit, 'phi')
  File "/Users/faith/ep-stan/epstan/util.py", line 483, in copy_fit_samples
    src = fit.sim['samples'][c]['chains'][param_name_d][warmup:]
KeyError: 'phi[0]'
Traceback (most recent call last):
  File "/Users/faith/ep-stan/experiment/fit.py", line 1194, in <module>
    main(model_name, conf)
  File "/Users/faith/ep-stan/experiment/fit.py", line 369, in main
    seed = conf.seed_ep
  File "/Users/faith/ep-stan/epstan/method.py", line 1233, in run
    seed = seeds[cur_iter, k]
  File "/Users/faith/ep-stan/epstan/method.py", line 368, in tilted
    samp, lastsamp, dur, msteps, mrhat = q.get()
  File "/Users/faith/anaconda3/envs/py3.7/lib/python3.7/multiprocessing/queues.py", line 94, in get
    res = self._recv_bytes()
  File "/Users/faith/anaconda3/envs/py3.7/lib/python3.7/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/Users/faith/anaconda3/envs/py3.7/lib/python3.7/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/Users/faith/anaconda3/envs/py3.7/lib/python3.7/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
KeyboardInterrupt

![image](https://user-images.githubusercontent.com/16201784/83707777-cdaec480-a5e8-11ea-8ce6-43227c0a78c1.png)

Environment:
aiohttp==3.5.4
albumentations==0.4.5
altgraph==0.17
androguard==3.3.5
aniso8601==8.0.0
apkid==2.0.3
appnope==0.1.0
asgiref==3.2.3
asn1crypto==1.3.0
async-timeout==3.0.1
attrs==19.3.0
auditok==0.1.5
Automat==20.2.0
autopep8==1.5.2
autosub==0.5.5a0
backcall==0.1.0
beautifulsoup4==4.7.1
biplist==1.0.3
blinker==1.4
brotlipy==0.7.0
bs4==0.0.1
cachetools==4.0.0
certifi==2019.6.16
cffi==1.12.3
chardet==3.0.4
click==6.7
colorama==0.4.3
colorlog==4.1.0
colour==0.1.5
constantly==15.1.0
cryptography==2.8
cssselect==1.1.0
cycler==0.10.0
Cython==0.29.19
decorator==4.4.1
dicttoxml==1.7.4
distro==1.4.0
Django==3.0.2
django-redis==4.11.0
dlib==19.17.0
dnspython==1.16.0
fake-useragent==0.1.11
ffmpeg-normalize==1.15.8
flasgger==0.9.4
Flask==1.1.2
Flask-RESTful==0.3.8
frida==12.8.9
frida-tools==6.0.1
future==0.17.1
google-api-core==1.16.0
google-auth==1.11.3
google-cloud-speech==1.3.2
google-play-scraper==0.0.1.2
googleapis-common-protos==1.51.0
googletrans==2.4.0
grpcio==1.27.2
gunicorn==19.4.1
h11==0.7.0
h2==3.1.1
h5py==2.10.0
hpack==3.0.0
html5lib==1.0.1
http-tools==1.0.2
hyperframe==5.2.0
hyperlink==19.0.0
idna==2.8
imageio==2.8.0
imgaug==0.2.6
importlib-metadata==1.5.0
imutils==0.5.2
incremental==17.5.0
ipykernel==5.1.3
ipython==7.11.1
ipython-genutils==0.2.0
itsdangerous==0.24
jedi==0.15.2
Jinja2==2.11.2
joblib==0.14.1
jsonschema==3.2.0
jupyter-client==5.3.4
jupyter-core==4.6.1
kaitaistruct==0.8
Keras==2.3.1
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.0
kiwisolver==1.1.0
langcodes-py2==1.2.0
ldap3==2.5.2
libmagic==1.0
libopencv==0.0.1
lxml==4.3.4
macholib==1.14
manimlib==0.1.10
MarkupSafe==0.23
matplotlib==3.1.1
mechanize==0.4.5
mistune==0.8.4
mitmproxy==4.0.4
mkl-fft==1.0.15
mkl-random==1.1.0
mkl-service==2.3.0
more-itertools==8.2.0
multidict==4.5.2
munch==2.5.0
mysqlclient==1.4.6
networkx==2.4
numpy==1.18.1
olefile==0.46
opencv-contrib-python==4.1.0.25
opencv-python==3.4.2.17
oscrypto==1.1.0
packaging==20.1
pandas==0.24.2
parsel==1.5.2
parso==0.5.2
passlib==1.7.2
pdfkit==0.6.1
pexpect==4.7.0
pickleshare==0.7.5
Pillow==5.2.0
pretrainedmodels==0.7.4
progressbar==2.5
progressbar2==3.50.0
prompt-toolkit==3.0.3
Protego==0.1.16
protobuf==3.11.3
psutil==5.6.7
ptyprocess==0.6.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycairo==1.19.1
pycodestyle==2.5.0
pycparser==2.19
pycrypto==2.6.1
PyDispatcher==2.0.5
pydot==1.4.1
pydub==0.23.0
Pygments==2.5.2
PyHamcrest==2.0.2
PyInstaller==3.6
pyOpenSSL==19.1.0
pyparsing==2.2.2
pyperclip==1.6.5
PyQt5==5.14.1
PyQt5-sip==12.7.1
pyrsistent==0.15.7
PySocks==1.7.1
pystan==2.19.1.1
pysubs2==0.2.4
pytesseract==0.3.4
python-dateutil==2.8.1
python-magic==0.4.10
python-utils==2.4.0
pytz==2019.3
PyWavelets==1.1.1
PyYAML==5.3
pyzmq==18.1.1
queuelib==1.5.0
redis==3.3.11
requests==2.22.0
rq==1.2.2
rsa==4.0
ruamel.yaml==0.15.100
scikit-image==0.16.2
scikit-learn==0.22.1
scipy==1.3.0
Scrapy==2.1.0
service-identity==18.1.0
shelljob==0.5.6
sip==5.1.1
six==1.12.0
sklearn==0.0
sortedcontainers==2.0.5
soupsieve==1.9.2
sqlparse==0.3.0
toml==0.10.0
torch==1.1.0
torchvision==0.6.0
tornado==5.1.1
tqdm==4.24.0
traitlets==4.3.3
Twisted==20.3.0
unicodecsv==0.14.1
urllib3==1.25.7
urwid==2.0.1
w3lib==1.21.0
waitress==1.4.2
wcwidth==0.1.8
webencodings==0.5.1
websockets==8.1
Werkzeug==1.0.1
whitenoise==5.0.1
wrapcache==1.0.8
wsproto==0.11.0
XlsxWriter==1.2.7
xmltodict==0.12.0
yara-python==3.10.0
yarl==1.3.0
zipp==2.1.0
zope.interface==5.1.0

OS: MacOS 10.14.6

**Comment by realkrantz** [comment]
Hi @avehtari et al. Would it be possible to translate from Python to R the implementation of https://arxiv.org/abs/1412.4869? Thanks.
